name: FoxCore
main: live.cakeyfox.FoxCore.FoxCorePlugin
version: 1.0
api-version: 1.20
author: CakeyFox
description: FoxCore is a module for all FoxLand plugins.
loadbefore:
  - nLogin
commands:
  connectToWebsocket:
    description: Connect to the CakeyFox Websocket.
    usage: /<command>
    permission: FoxCore.connectToWebsocket